image: node:18-slim

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "@altpay:registry=https://git.macellan.net/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - yarn install
    - yarn build
    - npm version $CI_COMMIT_TAG --no-git-tag-version
    - npm publish
  tags:
    - docker_runner
  only:
    - tags
